var buzzwords = [
"Action this/that",
"Alignment",
"At the end of the day",
"Break through the clutter",
"Bring to the table",
"Buzzword",
"Clear goal",
"Disruptive innovation",
"Diversity",
"Empowerment",
"Exit strategy",
"Face time",
"Generation X",
"Globalization",
"Going forward",
"Grow",
"Headlights",
"Holistic approach",
"Impact",
"Leverage",
"Millennial",
"Moving forward",
"New normal",
"On the runway",
"Organic growth",
"Outside the box",
"Paradigm",
"Paradigm shift",
"Proactive",
"Push the envelope",
"Reach out",
"Sea change",
"Sisterhood",
"Spin-up",
"Strategic Communication",
"Streamline",
"Survival strategy",
"Sustainability",
"Synergy",
"Unpack",
"Wellness",
"Wheelhouse",
"Win-win",
"Accountable talk",
"Higher-order thinking",
"Invested in",
"Run like a business",
"Student engagement",
"Common Core",
"Bloom's Taxonomy",
"Differentiated instruction",
"Digital Literacy",
"Flipped Classroom",
"Guided Reading",
"Instructional Scaffolding",
"Multiple Intelligences",
"Project-Based Learning",
"Adaptive Learning",
"Brain Break",
"Cooperative Learning",
"Analytics",
"Ballpark figure",
"Bandwidth",
"Business-to-Business",
"Business-to-Consumer",
"Best of Breed",
"Best practices",
"Bizmeth",
"Brand",
"Brick-and-mortar",
"Business process outsourcing",
"Buzzword compliant",
"Capability building",
"Cherry-Pick",
"Circle Back",
"Client-centric",
"Cloud computing",
"Close the loop",
"Co-opetition",
"Come-to-Jesus moment",
"Content marketing",
"Core competency",
"Creative",
"Customer-centric",
"Deep dive",
"Dove tail",
"Downsizing",
"Drill down",
"Drinking the Kool-Aid",
"Early-stage",
"Employer branding",
"Eating your own dogfood",
"Enable",
"Entitlement",
"Enterprise",
"Event horizon",
"Eyeballs",
"Free value",
"Fulfilment issues",
"Generation Y",
"Granular",
"Herding cats",
"Holistic",
"Hyperlocal",
"Innovation",
"Innovative",
"Knowledge Process Outsourcing",
"Leverage",
"Logistics",
"Long Tail",
"Low Hanging Fruit",
"Make it pop",
"Mindshare",
"Mission Critical",
"Management Visibility",
"New economy",
"Next generation",
"Offshoring",
"Opportunities",
"Pain point",
"Paralysis by Analysis",
"Part of our DNA",
"Passionate",
"Peel back the onion",
"Pick and Shovel Work",
"Profit center",
"Quick-win",
"Return on Investment",
"Reverse fulfilment",
"Rightshoring",
"Seamless (integration)",
"Serum",
"Share options",
"Short Runway",
"Silo",
"Social Currency",
"Socialize",
"Solution",
"SOX",
"Sustainability",
"Storytelling",
"Startup",
"Strategy",
"Synergy",
"Take Offline",
"Talent Relationship Management",
"Tee off",
"Touch Base",
"Touchpoint",
"Upselling",
"Upcycling",
"Value-added",
"Visibility",
"Water under the bridge",
"We are who we are",
"4G",
"Aggregator",
"Agile",
"Ajax",
"Algorithm",
"Benchmarking",
"Back-end",
"Beta",
"Big data",
"Bleeding edge",
"Blog",
"Bring your own Device",
"Bricks-and-clicks",
"Clickthrough",
"Cloud",
"CloudOps",
"Collaboration",
"Content management",
"Content Management System",
"Convergence",
"Cross-platform",
"Cyber-physical Systems (CPS)",
"Datafication",
"Data mining",
"Data science",
"Deep dive",
"Deep web",
"Design pattern",
"DevOps",
"Digital divide",
"Digital Remastering",
"Digital Rights Management",
"Digital signage",
"Disruptive Technologies",
"Document management",
"Dot-bomb",
"____-Driven Development",
"E-learning",
"End-to-End",
"Engine",
"Enterprise Content Management",
"Enterprise Service Bus â€“ also known as ESB.",
"Evolution",
"Framework",
"Folksonomy",
"Fuzzy logic",
"Growth Hacking",
"HTML5",
"Immersion",
"Information superhighway",
"Internet of Things",
"Innovation",
"Machine Learning",
"Mashup",
"Microservices",
"Mobile",
"Modularity",
"Nanotechnology",
"Netiquette",
"NFV- Network Function virtualization",
"Next Generation",
"Object-Oriented Programming",
"Omnichannel",
"Pandering",
"Parsing",
"PaaS",
"Podcasting",
"Portal",
"Real-time",
"Responsive Web Design",
"Sensorization",
"SaaS",
"Scalability",
"Skeuomorphic",
"Social bookmarking",
"Social software",
"SDN- Software defined Networking",
"Spam",
"Sync-up",
"Systems Development Life-Cycle",
"Tagging",
"Think outside the box",
"Thought Leader",
"Transmedia",
"UC - Unified Communications",
"User generated content",
"Viral",
"Virtualization",
"Vlogging",
"Vortal",
"Web 2.0",
"Webinar",
"Weblog",
"Web services",
"Wikiality",
"Workflow",
"Big society",
"Information society",
"Political capital",
"Statist",
"Stakeholder"
];

module.exports = buzzwords;